server:
  port: 8081

spring:
  application:
    name: CLIENT-SERVICE
  config:
    import: optional:configserver:http://localhost:8888



  datasource:
    url: jdbc:mysql://localhost:3306/ms2
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    client:
      serverUrl:
        defaultZone:  http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0