---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: zipkin
  labels:
    app: zipkin

spec: 
  replicas: 1    
  template: 
    metadata: 
      name: zipkin
      labels:
        app: zipkin
    spec:                       # <- The correct place for the 'spec' field
      containers:
      - name: zipkin
        image: openzipkin/zipkin 
        ports:
        - containerPort: 9411

        
  selector:
    matchLabels:
      app: zipkin    

---
apiVersion: v1 
kind: Service 
metadata: 
  name: zipkin
spec:
  type: LoadBalancer
  selector:
    app: zipkin 
  ports:
    port: 9411
    targetPort: 9411
    nodePort: 53769   

...
