server:
  port: 8888
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RADHAKANT12/Micro-Config-Server
          clone-on-start: true
          default-label: main





eureka:
  client:
    serviceUrl:
      defaultZone: http://service:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true